#!/bin/bash
case "$1" in
   "c") bash ./c > output.txt
   ;;
   "java") bash ./java > output.txt
   ;;
   "python") bash ./python > output.txt
   ;;
   *) bash c > output.txt
      bash java >> output.txt
      bash python >> output.txt
   ;;
esac
echo '!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>"your choice" </title>
</head>
<body>
    <p>'>index1.html
 cat output.txt >>index1.html
 echo '</p>
</body>
</html>
'>>index1.html
echo "print after command_______________________________________"
cat index1.html >index.html
rm output.txt
echo "FROM httpd:2.4" > Dockerfile
echo "WORKDIR /my_app" >> Dockerfile
echo "COPY . ." >> Dockerfile
# echo "COPY . /usr/local/apache2/htdocs/" >> Dockerfile
