#!/bin/bash
export ENV_PRINT_IN_WEBSITE = "cat output"
export ENV_PRINT_IN_WEBSITE = "((cat output))"
# export -f -n ENV_PRINT_IN_WEBSITE = {cat output}
# export -f -n ENV_PRINT_IN_WEBSITE = [cat output]
echo "parameter language is: ------------------   $1"
case "$1" in
   "c") bash ./c > output
   ;;
   "java") bash ./java > output
   ;;
   "python") bash ./python > output
   ;;
   *) bash c > output
      bash java >> output
      bash python >> output
   ;;
esac
ENV_PRINT_IN_WEBSITE= $((cat output))
 
cat index.html
# comm = $((cat output))
# search = "language"
# sed -i "s/"language"/"$comm"/" ./index.txt
# mv index.txt index.html
# export output = bash ./output
# index.html contain $output then change 
