#!/bin/bash
echo "------------------   $1"
case "$1" in
   "c") bash ./C > output
   ;;
   "java") bash ./JAVA > output
   ;;
   "python") bash ./PYTHON > output
   ;;
   *) bash C > output
      bash JAVA >> output
      bash PYTHON >> output
   ;;
esac
cat output
# ENV_ = cat output
cat index.html
# comm = $((cat output))
# search = "language"
# sed -i "s/"language"/"$comm"/" ./index.txt
# mv index.txt index.html
# export output = bash ./output
# index.html contain $output then change 
